### ISSUE TITLE
Business usage is not allowed in Github Pages

### ISSUE THREAD

**Issue by MuhammadAnnaqeeb** [jacebenson/jace.pro#237]
While allowed in other services. for example Gitlab Pages explicitly states it is OK to use it for Business. This factor need a point in comparison.

**Comment by jacebenson** [comment]
Do you have links where it says it's okay and not okay on any of the services?

**Comment by jacebenson** [comment]
Github
> GitHub Pages is not intended for or allowed to be used as a free web hosting service to run your online business, e-commerce site, or any other website that is primarily directed at either facilitating commercial transactions or providing commercial software as a service (SaaS).
> 
> In addition, GitHub does not allow GitHub Pages to be used for certain purposes or activities. For a list of prohibited uses, see "GitHub's Additional Product Terms for GitHub Pages."
https://docs.github.com/en/github/working-with-github-pages/about-github-pages#prohibited-uses

**Comment by jacebenson** [comment]
Netlify

I looked and nothing says you can or cannot use for any personal or business website, however, their offerings do.

https://www.netlify.com/tos/

**Comment by jacebenson** [comment]
Cloudflare

I looked and nothing says you can or cannot use for any personal or business website, however, their offerings do.

https://pages.cloudflare.com/#pricing

**Comment by jacebenson** [comment]
Added  this.
Thanks @MuhammadAnnaqeeb
