### ISSUE TITLE
is it possible to use this end point mentioned in this post?

### ISSUE THREAD

**Issue by luffy3298** [jacebenson/jace.pro#242]
https://github.com/jacebenson/jace.pro/blob/master/src/post/2018-11-05-angular-do/index.md

i cannot use rest to post message

**Comment by jacebenson** [comment]
I don't know why you'd use /angular.do.  I just verified the Post button still uses this on UI16.  You should be able to recreate that post message to submit comments and work notes.  I would not use this though.  Instead I would use the table api or a custom rest end point or the newer graphql endpoints.

**Comment by luffy3298** [comment]
Thanks for confirming :) I was thinking, If servicenow uses it to post. why cant we use it

**Comment by jacebenson** [comment]
I'm going to close this.  If you have any q's let me know.
