### ISSUE TITLE
Some page have broken styling in the blog

### ISSUE THREAD

**Issue by victornoel** [jacebenson/jace.pro#243]
**Describe the bug**

Hi, thanks a lot for the great knowledge shared on your blog.

I noticed the page https://jace.pro/post/2020-12-17-cloudflare-pages-netlify-zeit-github-pages-and-gitlab-pages-where-to-host/ has a broken styling.

**Screenshots**

It looks like this on my computer:
![image](https://user-images.githubusercontent.com/160975/116807262-7aaffb00-ab32-11eb-90a7-941c2632ef7a.png)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser: Firefox
 - Version: 88.0

**Comment by jacebenson** [comment]
The page just didnt have any table styling.  I added some basic styles for tables.

**Comment by jacebenson** [comment]
Thanks for the feed back!
